CREATE DATABASE LibraryDatabase;
USE LibraryDatabase;

CREATE TABLE UserInfo(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(20) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  Rented VARCHAR(30)
);

CREATE TABLE BookInfo(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BookName VARCHAR(50) NOT NULL,
  BookPath VARCHAR(100) NOT NULL,
  Storage INT DEFAULT 0,
  Rented VARCHAR(30)
);

INSERT INTO BookInfo(BookName,BookPath) VALUES('CSSÈ¨ÍþÖ¸ÄÏ','/books/css.jpg');
